// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoeStore.Products.Infrastructure;

namespace ShoeStore.Products.Infrastructure.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20190914083542_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ssp")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShoeStore.Products.Domain.Catalogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Catalogues");
                });

            modelBuilder.Entity("ShoeStore.Products.Domain.CatalogueProduct", b =>
                {
                    b.Property<int>("CatalogueProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CatalogueId");

                    b.Property<int>("ProductId");

                    b.HasKey("CatalogueProductId");

                    b.HasIndex("CatalogueId");

                    b.HasIndex("ProductId");

                    b.ToTable("CatalogueProduct");
                });

            modelBuilder.Entity("ShoeStore.Products.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<decimal>("Cost");

                    b.Property<string>("LongDescription");

                    b.Property<string>("Name");

                    b.Property<int>("Rank");

                    b.Property<string>("ShortDescription");

                    b.Property<int>("Stock");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ShoeStore.Products.Domain.CatalogueProduct", b =>
                {
                    b.HasOne("ShoeStore.Products.Domain.Catalogue", "Catalogue")
                        .WithMany("CatalogueProducts")
                        .HasForeignKey("CatalogueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShoeStore.Products.Domain.Product", "Product")
                        .WithMany("CatalogueProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
